homepage:
  path: /
  defaults: { _controller: 'Smart\Controllers\IndexController::homeAction' }
login:
  path: /login
  defaults: { _controller: 'Smart\Controllers\IndexController::loginAction' }
register:
  path: /register
  defaults: { _controller: 'Smart\Controllers\IndexController::registerAction' }
logout:
  path: /logout
  defaults: { _controller: 'Smart\Controllers\IndexController::logoutAction' }
admin_index:
  path: /admin/test
  defaults: { _controller: 'Smart\Controllers\IndexController::testAction' }
locations:
  path: /locations
  defaults: { _controller: 'Smart\Controllers\IndexController::listLocationAction' }
new_location:
  path: /new-location
  defaults: { _controller: 'Smart\Controllers\IndexController::newLocationAction' }
managers:
  path: /managers
  defaults: { _controller: 'Smart\Controllers\IndexController::listManagersAction' }
new_manager:
  path: /new-manager
  defaults: { _controller: 'Smart\Controllers\IndexController::newManagerAction' }
state_list:
  path: /states/{countryId}
  defaults: { _controller: 'Smart\Controllers\IndexController::stateListAction' }
buy_stage_one:
  path: /buy/stage-1
  defaults: { _controller: 'Smart\Controllers\IndexController::buyerInfoAction' }  
buy_stage_two:
  path: /buy/stage-2
  defaults: { _controller: 'Smart\Controllers\IndexController::expressResponseAction' }  
