homepage:
  path: /
  defaults: { _controller: 'Smart\Controllers\IndexController::homeAction' }
login:
  path: /login
  defaults: { _controller: 'Smart\Controllers\IndexController::loginAction' }
register:
  path: /register
  defaults: { _controller: 'Smart\Controllers\IndexController::registerAction' }
logout:
  path: /logout
  defaults: { _controller: 'Smart\Controllers\IndexController::logoutAction' }
admin_index:
  path: /admin/test
  defaults: { _controller: 'Smart\Controllers\IndexController::testAction' }
locations:
  path: /locations
  defaults: { _controller: 'Smart\Controllers\BusinessController::listLocationAction' }
new_location:
  path: /locations/{id}
  defaults: { _controller: 'Smart\Controllers\BusinessController::editLocationAction' }
managers:
  path: /managers
  defaults: { _controller: 'Smart\Controllers\IndexController::listManagersAction' }
new_manager:
  path: /new-manager
  defaults: { _controller: 'Smart\Controllers\IndexController::newManagerAction' }
state_list:
  path: /states/{countryId}
  defaults: { _controller: 'Smart\Controllers\IndexController::stateListAction' }
buy_stage_one:
  path: /buy/stage-1
  defaults: { _controller: 'Smart\Controllers\IndexController::buyerInfoAction' }  
buy_stage_two:
  path: /buy/stage-2
  defaults: { _controller: 'Smart\Controllers\IndexController::expressResponseAction' }  
ajaxOrder:
  path: /ajax/update-order
  defaults: { _controller: 'Smart\Controllers\IndexController::ajaxOrderUpdateAction' }  
ajaxAusPostCalculator:
  path: /ajax/calculate-post
  defaults: { _controller: 'Smart\Controllers\IndexController::ajaxPostCalculateAction' }  
activate_user:
  path: /business/activate/{key}
  defaults: { _controller: 'Smart\Controllers\IndexController::activateBusinessAction' }  
payment_thanks:
  path: /payment/thanks
  defaults: { _controller: 'Smart\Controllers\IndexController::paymentThanksAction'}
buy_subscription:
  path: /probe-monitoring/{transactionid}
  defaults: { _controller: 'Smart\Controllers\IndexController::buyMonitoringAction' }
subscription_response:
  path: /subscription-response/
  defaults: { _controller: 'Smart\Controllers\IndexController::subscriptionResponseAction' }
resetAccessKey:
  path: /ajax/reste-key/{accesskey}/
  defaults: { _controller: 'Smart\Controllers\BusinessController::resetAccessKeyAction' }
    
    
